version: "3.7"

services:

  weblogic:
    container_name: weblogic
    image: node
    restart: always
    working_dir: /home/node/app
    volumes:
      - C:/Users/Gabi/Desktop/CUPIDR/weblogic:/home/node/app
    ports:
      - 80:80
      - 443:443
    command: "npm start"
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
  mysql:
    image: mysql:5.7
    restart: always
    ports: 
     - 3306:3306
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8000:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
volumes:
    mysql_data: